# Use latest jboss/base-jdk:11 image as the base
FROM jboss/base-jdk:11

# Set the WILDFLY_VERSION env variable
ARG WILDFLY_VERSION
ENV WILDFLY_VERSION=${WILDFLY_VERSION:-17.0.1.Final}
ARG WILDFLY_PATH
ENV WILDFLY_PATH=${WILDFLY_PATH}
ENV JBOSS_HOME /opt/jboss/wildfly

USER root
# Add the WildFly distribution to /opt, and make wildfly the owner of the extracted tar content
# Make sure the distribution is available from a well-known place
ADD $WILDFLY_PATH ./
RUN cd $HOME \
    && mv $(find /opt/jboss  -name "*$WILDFLY_VERSION" -type d -maxdepth 1) $JBOSS_HOME \
    && chown -R jboss:0 ${JBOSS_HOME} \
    && chmod -R g+rw ${JBOSS_HOME}

# Ensure signals are forwarded to the JVM process correctly for graceful shutdown
ENV LAUNCH_JBOSS_IN_BACKGROUND true

USER jboss

RUN /opt/jboss/wildfly/bin/add-user.sh admin-user test.12345 --silent

# Configure JSON logging
ADD logging.properties /opt/jboss/wildfly/standalone/configuration/logging.properties
ADD setup.cli /opt/jboss/setup.cli
ADD logging.properties /opt/jboss/wildfly/standalone/configuration/logging.properties

ENV DOCKERIZE_VERSION v0.6.1
RUN curl -O -L https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

CMD ./dockerize -wait tcp://fluentd:24224 -wait tcp://elasticsearch:9200 -timeout 120s \
    && /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0
